=== toxn/oegen-java/oegen-kiss.xsd
<?xml version="1.0"?>
<xs:schema xmlns="com.cdbs.oegen" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="com.cdbs.oegen" elementFormDefault="qualified"
>

	<xs:simpleType name="oebjectId">
		<xs:restriction base="xs:string" />
	</xs:simpleType>

	<xs:simpleType name="p2pRelType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="father" />
			<xs:enumeration value="mother" />
			<xs:enumeration value="child" />
			<xs:enumeration value="daughter" />
			<xs:enumeration value="son" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="gender">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Male" />
			<xs:enumeration value="Female" />
			<xs:enumeration value="Unknown" />
			<xs:enumeration value="Other" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="oebject" abstract="true">
		<xs:sequence>
			<xs:element name="comment" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:any namespace="http://www.w3.org/1999/xhtml" minOccurs="1"
							maxOccurs="unbounded" processContents="skip" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="id" type="oebjectId" />
	</xs:complexType>

	<xs:complexType name="person">
		<xs:complexContent>
			<xs:extension base="oebject">
				<xs:sequence>
					<xs:choice minOccurs="0" maxOccurs="3">
						<xs:element name="firstName" type="xs:string"/>
						<xs:element name="lastName" type="xs:string"/>
						<xs:element name="gender" type="gender"  />
					</xs:choice>
					<xs:choice minOccurs="0" maxOccurs="unbounded">
						<xs:element name="list" type="listOfPerson"/>
						<xs:element name="person" type="subperson" />
						<xs:element name="personRef" type="person2PersonRef" />
					</xs:choice>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="listOfPerson">
		<xs:sequence>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="person" type="person" />
				<xs:element name="personRef" type="personRef" />
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="of" type="p2pRelType" />
	</xs:complexType>

	<xs:complexType name="subperson">
		<xs:complexContent>

			<xs:extension base="person">
				<xs:attribute name="relation" type="p2pRelType" />
			</xs:extension>

		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="personRef">
		<xs:attribute name="ref" type="oebjectId" />
	</xs:complexType>

	<xs:complexType name="person2PersonRef">
		<xs:complexContent>
			<xs:extension base="personRef">
				<xs:attribute name="relation" type="p2pRelType" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:element name="oegendb">
		<xs:complexType>
			<xs:sequence minOccurs="0"
					maxOccurs="unbounded" >
				<xs:element name="person" type="person" minOccurs="0"
					maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="uniqueId">
			<xs:selector xpath="person|place" />
			<xs:field xpath="@id" />
		</xs:unique>
		<xs:keyref name="personRef" refer="uniqueId">
			<xs:selector xpath="personRef" />
			<xs:field xpath="@ref" />
		</xs:keyref>
	</xs:element>

</xs:schema>

=== toxn/oegen-java/oegen.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<oegendb xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="com.cdbs.oegen oegen-kiss.xsd"
>
	<person>
		<firstName>Old'pa</firstName>
		<lastName>Oiseau</lastName>
		<gender>Male</gender>
		<list of="child">
			<person>
				<firstName>Grand'pa</firstName>
				<lastName>Oiseau</lastName>
				<gender>Male</gender>
				<person relation="mother">
					<firstName>Old'ma</firstName>
					<lastName>Oiseau</lastName>
					<gender>Female</gender>
				</person>
				<list of="child">
					<person>
						<firstName>Ara</firstName>
						<lastName>Oiseau</lastName>
						<gender>Male</gender>
						<person relation="mother">
							<firstName>Granny</firstName>
							<lastName>Oiselle</lastName>
							<gender>Female</gender>
							<person relation="father">
								<firstName>Old'pa</firstName>
								<lastName>Oiselle</lastName>
								<gender>Male</gender>
							</person>
							<person relation="mother">
								<firstName>Old'ma</firstName>
								<lastName>Oiselle</lastName>
								<gender>Female</gender>
							</person>
							<list of="child">
								<person>
									<firstName>perroquet</firstName>
									<lastName>oiseau</lastName>
									<gender>Male</gender>
									<person relation="child">
										<firstName>moineau</firstName>
										<lastName>oiseau</lastName>
										<gender>Male</gender>
										<person relation="mother">
											<firstName>mésange</firstName>
											<lastName>geai</lastName>
											<gender>Female</gender>
											<person relation="father">
												<firstName>Grand'pa</firstName>
												<lastName>Geai</lastName>
												<gender>Male</gender>
												<person relation="father">
													<firstName>Old'pa</firstName>
													<lastName>Geai</lastName>
													<gender>Male</gender>
												</person>
												<person relation="mother">
													<firstName>Old'ma</firstName>
													<lastName>Geai</lastName>
													<gender>Female</gender>
												</person>
											</person>
											<person relation="mother">
												<firstName>Granny</firstName>
												<lastName>Mésange</lastName>
												<gender>Female</gender>
												<person relation="father">
													<firstName>Old'pa</firstName>
													<lastName>Mésange</lastName>
													<gender>Male</gender>
												</person>
												<person relation="mother">
													<firstName>Old'ma</firstName>
													<lastName>Mésange</lastName>
													<gender>Female</gender>
												</person>
											</person>
											<person relation="child">
												<firstName>alouette</firstName>
												<lastName>oiseau</lastName>
												<gender>Female</gender>
											</person>
											<person relation="child">
												<firstName>Pélican</firstName>
												<lastName>Oiseau</lastName>
												<gender>Male</gender>
											</person>
											<person relation="child">
												<firstName>Orphan</firstName>
												<lastName>Of Father</lastName>
												<gender>Other</gender>
											</person>
										</person>
									</person>
									<person relation="child">
										<firstName>Orphan</firstName>
										<lastName>Of Mother</lastName>
										<gender>Unknown</gender>
									</person>
								</person>
							</list>
						</person>
					</person>
				</list>
			</person>
		</list>
	</person>
</oegendb>
